name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Modify the Node.js version as needed

      - name: Install dependencies
        run: npm install # Replace with your dependency installation command

      - name: Build
        run: npm run build # Replace with your build command

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_API_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: ./ # Modify this path as needed
