name: "My Workflow"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # This step checks out your code
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }} # Make sure this name matches your secret name
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: ./ # If your built files are in a different directory, change this
